FROM node:18-alpine3.14

WORKDIR /app_frontend
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin
# RUN apk update && apk add bash
RUN npm i -g @nestjs/cli
EXPOSE 3005:3005

ENTRYPOINT npm install && npm start
