version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14.3-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./database/database.env
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - ./database/database-data:/var/lib/postgresql/data
    command: postgres -c stats_temp_directory=/tmp
    networks:
      - database
    hostname: db
    extra_hosts:
        - "host.docker.internal:host-gateway"

  backend:
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: Dockerfile-backend
    env_file:
      - ./backend/backend.env
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app_backend
    networks:
      - database
    restart: always
    container_name: backend_app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile-frontend
    volumes:
    - ./frontend/:/app_frontend
    ports:
      - "3005:3005"
      - "443:443"
    restart: always
    container_name: frontend_app

networks:
  database:
    driver: bridge
