FROM nginx:1.22.0-alpine

COPY ./build /usr/share/nginx/html/ft_transcendence
COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY ./certs/nginx.key /etc/ssl/private/nginx.key
COPY ./certs/nginx.crt /etc/ssl/certs/nginx.crt
COPY ./certs/self-signed.conf /etc/nginx/snippets/self-signed.conf
EXPOSE 443:443
EXPOSE 3005:3005
CMD ["nginx", "-g", "daemon off;"]