export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const DISCONNECT_USER = "DISCONNECT_USER";
export const SET_USER_INGAME = "SET_USER_INGAME";
export const UNSET_USER_INGAME = "UNSET_USER_INGAME";
export const SET_ID_GAME = "SET_ID_GAME";
export const UPDATE_AVATAR = "UPDATE_AVATAR";
export const CONNECTION_SERVER_APPROVED = "CONNECTION_SERVER_APPROVED";
